In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [56]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [57]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [47]:
#credits.values

In [58]:
credits.shape

(4803, 4)

In [59]:
movie = movies.merge(credits, on='title')

In [60]:
movie.shape

(4809, 23)

In [61]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [62]:
moviess = movie[['movie_id','genres','cast','crew','title','keywords','overview']]
moviess.head(2)

,movie_id,genres,cast,crew,title,keywords,overview
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."

In [10]:
moviess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   genres    4809 non-null   object
 2   cast      4809 non-null   object
 3   crew      4809 non-null   object
 4   title     4809 non-null   object
 5   keywords  4809 non-null   object
 6   overview  4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [65]:
moviess.isnull().sum()

movie_id    0
genres      0
cast        0
crew        0
title       0
keywords    0
overview    0
dtype: int64

In [64]:
moviess.dropna(inplace = True)

/tmp/ipykernel_11010/616746707.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess.dropna(inplace = True)

In [66]:
moviess.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [67]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [68]:
def convert(obj):
    lis = []
    for i in ast.literal_eval(obj):
        lis.append(i['name'])
    return lis

In [69]:
moviess['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [70]:
moviess['genres'] = moviess['genres'].apply(convert)

/tmp/ipykernel_11010/3294966255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['genres'] = moviess['genres'].apply(convert)

In [71]:
moviess['keywords'] = moviess['keywords'].apply(convert)

/tmp/ipykernel_11010/3895651793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['keywords'] = moviess['keywords'].apply(convert)

In [73]:
def convert1(obj):
    lis = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            lis.append(i['name'])
            counter+=1
        else:
            break
    return lis

In [72]:
moviess['cast'] = moviess['cast'].apply(convert1)

/tmp/ipykernel_11010/4255381580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['cast'] = moviess['cast'].apply(convert1)

In [74]:
moviess.head(1)

,movie_id,genres,cast,crew,title,keywords,overview
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di..."

In [75]:
def fetch_dir(obj):
    lis = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            lis.append(i['name'])
            break
    return lis

In [76]:
moviess['crew'] = moviess['crew'].apply(fetch_dir)

/tmp/ipykernel_11010/3652100376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['crew'] = moviess['crew'].apply(fetch_dir)

In [23]:
moviess.head(1)

,movie_id,genres,cast,crew,title,keywords,overview
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],Avatar,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di..."

In [77]:
moviess['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [78]:
moviess['overview'] = moviess['overview'].apply(lambda x:x.split())

/tmp/ipykernel_11010/2100012213.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['overview'] = moviess['overview'].apply(lambda x:x.split())

In [79]:
moviess.head(1)

,movie_id,genres,cast,crew,title,keywords,overview
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],Avatar,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin..."

In [80]:
moviess['crew'].apply(lambda x:[i.replace(' ','') for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [81]:
moviess['crew'] = moviess['crew'].apply(lambda x:[i.replace(' ','') for i in x])
moviess['genres'] = moviess['genres'].apply(lambda x:[i.replace(' ','') for i in x])
moviess['cast'] = moviess['cast'].apply(lambda x:[i.replace(' ','') for i in x])
moviess['keywords'] = moviess['keywords'].apply(lambda x:[i.replace(' ','') for i in x])

/tmp/ipykernel_11010/3727192120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['crew'] = moviess['crew'].apply(lambda x:[i.replace(' ','') for i in x])
/tmp/ipykernel_11010/3727192120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['genres'] = moviess['genres'].apply(lambda x:[i.replace(' ','') for i in x])
/tmp/ipykernel_11010/3727192120.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['cast'] = moviess['cast'].apply(lambda x:[i.replace(' ','') for i in x])
/tmp/ipykernel_11010/3727192120.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['keywords'] = moviess['keywords'].apply(lambda x:[i.replace(' ','') for i in x])

In [82]:
moviess.head(1)

,movie_id,genres,cast,crew,title,keywords,overview
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."

In [83]:
moviess['tags'] = moviess['crew'] + moviess['genres'] + moviess['cast'] + moviess['keywords']

/tmp/ipykernel_11010/3395674310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviess['tags'] = moviess['crew'] + moviess['genres'] + moviess['cast'] + moviess['keywords']

In [31]:
moviess.head(1)

,movie_id,genres,cast,crew,title,keywords,overview,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[JamesCameron, Action, Adventure, Fantasy, Sci..."

In [84]:
data = moviess[['movie_id','title','tags']]
data.head()

,movie_id,title,tags
0,19995,Avatar,"[JamesCameron, Action, Adventure, Fantasy, Sci..."
1,285,Pirates of the Caribbean: At World's End,"[GoreVerbinski, Adventure, Fantasy, Action, Jo..."
2,206647,Spectre,"[SamMendes, Action, Adventure, Crime, DanielCr..."
3,49026,The Dark Knight Rises,"[ChristopherNolan, Action, Crime, Drama, Thril..."
4,49529,John Carter,"[AndrewStanton, Action, Adventure, ScienceFict..."

In [85]:
data['tags'].apply(lambda x: ' '.join(x))

0       JamesCameron Action Adventure Fantasy ScienceF...
1       GoreVerbinski Adventure Fantasy Action JohnnyD...
2       SamMendes Action Adventure Crime DanielCraig C...
3       ChristopherNolan Action Crime Drama Thriller C...
4       AndrewStanton Action Adventure ScienceFiction ...
                              ...
4804    RobertRodriguez Action Crime Thriller CarlosGa...
4805    EdwardBurns Comedy Romance EdwardBurns KerryBi...
4806    ScottSmith Comedy Drama Romance TVMovie EricMa...
4807        DanielHsia DanielHenney ElizaCoupe BillPaxton
4808    BrianHerzlinger Documentary DrewBarrymore Bria...
Name: tags, Length: 4806, dtype: object

In [86]:
data['tags'] = data['tags'].apply(lambda x: ' '.join(x))

/tmp/ipykernel_11010/3091122404.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['tags'].apply(lambda x: ' '.join(x))

In [87]:
data.head()

,movie_id,title,tags
0,19995,Avatar,JamesCameron Action Adventure Fantasy ScienceF...
1,285,Pirates of the Caribbean: At World's End,GoreVerbinski Adventure Fantasy Action JohnnyD...
2,206647,Spectre,SamMendes Action Adventure Crime DanielCraig C...
3,49026,The Dark Knight Rises,ChristopherNolan Action Crime Drama Thriller C...
4,49529,John Carter,AndrewStanton Action Adventure ScienceFiction ...

In [88]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [89]:
def stem(text):
    w = []
    for i in text.split():
        w.append(ps.stem(i))
    return " ".join(w)

In [90]:
data['tags'] = data['tags'].apply(stem)

/tmp/ipykernel_11010/2997483169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['tags'].apply(stem)

In [91]:
data['tags'] = data['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_11010/3172751869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['tags'].apply(lambda x:x.lower())

In [92]:
data.head()

,movie_id,title,tags
0,19995,Avatar,jamescameron action adventur fantasi sciencefi...
1,285,Pirates of the Caribbean: At World's End,goreverbinski adventur fantasi action johnnyde...
2,206647,Spectre,sammend action adventur crime danielcraig chri...
3,49026,The Dark Knight Rises,christophernolan action crime drama thriller c...
4,49529,John Carter,andrewstanton action adventur sciencefict tayl...

In [93]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 4000, stop_words = 'english')

In [94]:
cv.fit_transform(data['tags']).toarray().shape

(4806, 4000)

In [95]:
vector = cv.fit_transform(data['tags']).toarray()

In [96]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0])

In [97]:
cv.get_feature_names_out()

array(['16thcenturi', '17thcenturi', '18thcenturi', ..., 'zoo',
       'zooeydeschanel', 'zoëkravitz'], dtype=object)

In [98]:
from sklearn.metrics.pairwise import cosine_similarity

In [99]:
similarity  = cosine_similarity(vector)

In [100]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])[1:6]

[(47, 0.3922322702763681),
 (83, 0.3508232077228117),
 (2374, 0.3508232077228117),
 (61, 0.3396831102433787),
 (2405, 0.3235751144647171)]

In [101]:
def recommend(movie):
    movie_index = data[data['title'] == movie].index[0]
    distance = similarity[ movie_index]
    movie_list = sorted(list(enumerate(distance)), reverse = True, key = lambda x:x[1])[1:6]

    for i in movie_list:
        print(data.iloc[i[0]].title)

In [102]:
recommend('Avatar')

Star Trek Into Darkness
The Lovers
Megaforce
Jupiter Ascending
Aliens

In [103]:
import pickle

In [104]:
pickle.dump(data,open('movies.pkl', 'wb'))

In [105]:
data['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [106]:
pickle.dump(data.to_dict(),open('movies_dict.pkl', 'wb'))

In [107]:
pickle.dump(similarity,open('similarity', 'wb'))